import React, { useState } from 'react'
import {
  checkboxColumn,
  Column,
  DataSheetGrid,
  isoDateColumn,
  keyColumn,
  textColumn,
} from '../../src'
import '../../src/style.css'

type Row = {
  active: boolean
  firstName: string | null
  lastName: string | null
  date: string | null
  test?: {
    data: string
  }
  arrayTestNest1: { data: string }[]
  arrayTestNest2: { data: string }[][]
}

function App() {
  const [data, setData] = useState<any[]>(DATA);
  const columns: Column<any>[] = [
    {
      ...keyColumn<any>('user.account', textColumn),
      title: 'ユーザーアカウント',
      minWidth: 200,
      validators: [
        (value) => {
          if (!value?.user?.account) {
            return 'アカウントが必要です'
          }
        },
      ],
    },
    {
      ...keyColumn<any>('user.name', textColumn),
      title: 'ユーザー名',
      minWidth: 200,
      disabled: true,
    },
    {
        ...keyColumn<any>('test.date', isoDateColumn),
        title: '日付',
    },
    ...authList.map((auth, i) => ({
      ...keyColumn<any>(`auth.${i}.isEnabled`, checkboxColumn),
      title: auth.title,
    })),
  ];

  return (
    <div
      style={{
        margin: '50px',
        padding: '50px',
        maxWidth: '900px',
        background: '#f3f3f3',
        height: '500px',
      }}
    >
      <DataSheetGrid value={data} onChange={setData} columns={columns} />
    </div>
  )
}

export default App


const DATA = [
  {
      "id": "56561f52-9161-47af-949e-118f4eba0698",
      "user": {
          "account": "ss@ss",
          "name": "aa aa"
      },
      "auth": [
          {
              "id": "04a3e85d-c901-44d4-9761-748790523279",
              "isEnabled": false
          },
          {
              "id": "8450161e-acd3-4c27-b2c3-fc0be3ecdebb",
              "isEnabled": false
          },
          {
              "id": "d0eba3ac-2eee-4fe2-8d31-d46910524dad",
              "isEnabled": true
          },
          {
              "id": "3df8c683-bab5-4cc9-8e0f-b7dd13089209",
              "isEnabled": true
          },
          {
              "id": "6aa310c4-483c-41d2-ba48-a42ec65a705b",
              "isEnabled": true
          },
          {
              "id": "91152d03-8bd4-400e-acad-882e506cdc0b",
              "isEnabled": true
          },
          {
              "id": "c26efcca-0b6f-463e-b129-2db9f9a54fb2",
              "isEnabled": true
          },
          {
              "id": "5f44dc98-ee7e-4587-8fbf-fb9f080b392b",
              "isEnabled": true
          },
          {
              "id": "4db5a9db-a2b3-475a-a227-fc564af89bd4",
              "isEnabled": true
          },
          {
              "id": "9795400e-344e-4a56-ad75-7fa75d5f6ef0",
              "isEnabled": true
          },
          {
              "id": "97062e60-554d-41e4-bf5b-22060f77c4b8",
              "isEnabled": true
          },
          {
              "id": "2920792c-b9a7-470e-987c-43694cdfaed5",
              "isEnabled": true
          },
          {
              "id": "3f4c476e-1afa-4d7e-b831-8ced1c37d2ea",
              "isEnabled": true
          },
          {
              "id": "f8dd00b0-1718-4b6b-a087-aac3507dc655",
              "isEnabled": true
          },
          {
              "id": "f06a3775-536b-46ca-8c4b-2e8e60573c4a",
              "isEnabled": true
          },
          {
              "id": "a8bd796e-db58-4113-b66b-7563f0324604",
              "isEnabled": true
          },
          {
              "id": "5d6765b9-8996-4a5d-b71d-676526fccb67",
              "isEnabled": true
          }
      ]
  },
  {
      "id": "2f827ac5-e66f-40fe-816d-e60d876727d0",
      "user": {
          "account": "bb@bb",
          "name": "bb bb"
      },
      "auth": [
          {
              "id": "04a3e85d-c901-44d4-9761-748790523279",
              "isEnabled": true
          },
          {
              "id": "8450161e-acd3-4c27-b2c3-fc0be3ecdebb",
              "isEnabled": true
          },
          {
              "id": "d0eba3ac-2eee-4fe2-8d31-d46910524dad",
              "isEnabled": true
          },
          {
              "id": "3df8c683-bab5-4cc9-8e0f-b7dd13089209",
              "isEnabled": true
          },
          {
              "id": "6aa310c4-483c-41d2-ba48-a42ec65a705b",
              "isEnabled": true
          },
          {
              "id": "91152d03-8bd4-400e-acad-882e506cdc0b",
              "isEnabled": true
          },
          {
              "id": "c26efcca-0b6f-463e-b129-2db9f9a54fb2",
              "isEnabled": true
          },
          {
              "id": "5f44dc98-ee7e-4587-8fbf-fb9f080b392b",
              "isEnabled": true
          },
          {
              "id": "4db5a9db-a2b3-475a-a227-fc564af89bd4",
              "isEnabled": true
          },
          {
              "id": "9795400e-344e-4a56-ad75-7fa75d5f6ef0",
              "isEnabled": true
          },
          {
              "id": "97062e60-554d-41e4-bf5b-22060f77c4b8",
              "isEnabled": true
          },
          {
              "id": "2920792c-b9a7-470e-987c-43694cdfaed5",
              "isEnabled": true
          },
          {
              "id": "3f4c476e-1afa-4d7e-b831-8ced1c37d2ea",
              "isEnabled": true
          },
          {
              "id": "f8dd00b0-1718-4b6b-a087-aac3507dc655",
              "isEnabled": true
          },
          {
              "id": "f06a3775-536b-46ca-8c4b-2e8e60573c4a",
              "isEnabled": true
          },
          {
              "id": "a8bd796e-db58-4113-b66b-7563f0324604",
              "isEnabled": true
          },
          {
              "id": "5d6765b9-8996-4a5d-b71d-676526fccb67",
              "isEnabled": true
          }
      ]
  }
];

const authList = [
  {
      "id": "04a3e85d-c901-44d4-9761-748790523279",
      "title": "初期設定用メニュー",
      "personalSchedule": true,
      "departmentPlan": true,
      "yearSchedule": true,
      "message": true,
      "creation": true,
      "creationList": true,
      "requestList": true,
      "release": true,
      "documentAndRecordSearch": true,
      "editPublishSettings": true,
      "readingStatus": true,
      "editVersionNumber": false,
      "fileUpload": true,
      "corrective": true,
      "internalAuditCorrective": true,
      "internalAuditPlanList": true,
      "internalAuditList": true,
      "internalAuditMemberList": true,
      "personalMenu": true,
      "evaluatorMenu": true,
      "skillEvaluationPlan": true,
      "specificBusinessList": true,
      "documentAndRecord": true,
      "correctiveReport": true,
      "internalAuditReport": true,
      "fishbone": true,
      "organizationsMaster": true,
      "positionsMaster": true,
      "authoritiesMaster": true,
      "usersMaster": true,
      "directoriesMaster": true,
      "tagsMaster": true,
      "performancesMaster": true,
      "skillsMaster": true,
      "yearScheduleMaster": true,
      "qualityTargetMaster": true,
      "internalAuditMaster": true,
      "templatesMaster": true,
      "documentSelectionMaster": true,
      "approvalRoutesMaster": true,
      "mailSettingsMaster": true,
      "changedMasterHistory": true,
      "modeSwitching": true,
      "editSchedule": false,
      "absenceInformed": false,
      "templateRevisionCompleteInformed": false,
      "isProgressManagement": false,
      "confirmInform": false,
      "confirmPublish": false,
      "displayHistory": false,
      "correctiveInformed": false,
      "changeResponsible": false,
      "startCirculation": false,
      "templateWithdraw": false,
      "editableInternalAuditPlan": false,
      "changeResponsibleInternalAudit": false
  },
  {
      "id": "8450161e-acd3-4c27-b2c3-fc0be3ecdebb",
      "title": "マスター管理者用メニュー",
      "personalSchedule": true,
      "departmentPlan": true,
      "yearSchedule": true,
      "message": true,
      "creation": true,
      "creationList": true,
      "requestList": true,
      "release": true,
      "documentAndRecordSearch": true,
      "editPublishSettings": true,
      "readingStatus": true,
      "editVersionNumber": false,
      "fileUpload": true,
      "corrective": true,
      "internalAuditCorrective": true,
      "internalAuditPlanList": true,
      "internalAuditList": true,
      "internalAuditMemberList": true,
      "personalMenu": true,
      "evaluatorMenu": true,
      "skillEvaluationPlan": true,
      "specificBusinessList": true,
      "documentAndRecord": true,
      "correctiveReport": true,
      "internalAuditReport": true,
      "fishbone": true,
      "organizationsMaster": true,
      "positionsMaster": true,
      "authoritiesMaster": true,
      "usersMaster": true,
      "directoriesMaster": true,
      "tagsMaster": true,
      "performancesMaster": true,
      "skillsMaster": true,
      "yearScheduleMaster": true,
      "qualityTargetMaster": true,
      "internalAuditMaster": true,
      "templatesMaster": true,
      "documentSelectionMaster": true,
      "approvalRoutesMaster": true,
      "mailSettingsMaster": true,
      "changedMasterHistory": true,
      "modeSwitching": true,
      "editSchedule": false,
      "absenceInformed": false,
      "templateRevisionCompleteInformed": false,
      "isProgressManagement": false,
      "confirmInform": false,
      "confirmPublish": false,
      "displayHistory": false,
      "correctiveInformed": false,
      "changeResponsible": false,
      "startCirculation": false,
      "templateWithdraw": false,
      "editableInternalAuditPlan": false,
      "changeResponsibleInternalAudit": false
  },
  {
      "id": "d0eba3ac-2eee-4fe2-8d31-d46910524dad",
      "title": "要員用メニュー",
      "personalSchedule": true,
      "departmentPlan": true,
      "yearSchedule": true,
      "message": true,
      "creation": true,
      "creationList": true,
      "requestList": true,
      "release": true,
      "documentAndRecordSearch": true,
      "editPublishSettings": true,
      "readingStatus": true,
      "editVersionNumber": false,
      "fileUpload": true,
      "corrective": true,
      "internalAuditCorrective": true,
      "internalAuditPlanList": true,
      "internalAuditList": true,
      "internalAuditMemberList": true,
      "personalMenu": true,
      "evaluatorMenu": true,
      "skillEvaluationPlan": true,
      "specificBusinessList": true,
      "documentAndRecord": true,
      "correctiveReport": true,
      "internalAuditReport": true,
      "fishbone": true,
      "organizationsMaster": false,
      "positionsMaster": false,
      "authoritiesMaster": false,
      "usersMaster": false,
      "directoriesMaster": false,
      "tagsMaster": false,
      "performancesMaster": false,
      "skillsMaster": false,
      "yearScheduleMaster": false,
      "qualityTargetMaster": false,
      "internalAuditMaster": false,
      "templatesMaster": false,
      "documentSelectionMaster": false,
      "approvalRoutesMaster": false,
      "mailSettingsMaster": false,
      "changedMasterHistory": false,
      "modeSwitching": false,
      "editSchedule": false,
      "absenceInformed": false,
      "templateRevisionCompleteInformed": false,
      "isProgressManagement": false,
      "confirmInform": false,
      "confirmPublish": false,
      "displayHistory": false,
      "correctiveInformed": false,
      "changeResponsible": false,
      "startCirculation": false,
      "templateWithdraw": false,
      "editableInternalAuditPlan": false,
      "changeResponsibleInternalAudit": false
  },
  {
      "id": "3df8c683-bab5-4cc9-8e0f-b7dd13089209",
      "title": "版数編集",
      "personalSchedule": false,
      "departmentPlan": false,
      "yearSchedule": false,
      "message": false,
      "creation": false,
      "creationList": false,
      "requestList": false,
      "release": false,
      "documentAndRecordSearch": false,
      "editPublishSettings": false,
      "readingStatus": false,
      "editVersionNumber": true,
      "fileUpload": false,
      "corrective": false,
      "internalAuditCorrective": false,
      "internalAuditPlanList": false,
      "internalAuditList": false,
      "internalAuditMemberList": false,
      "personalMenu": false,
      "evaluatorMenu": false,
      "skillEvaluationPlan": false,
      "specificBusinessList": false,
      "documentAndRecord": false,
      "correctiveReport": false,
      "internalAuditReport": false,
      "fishbone": false,
      "organizationsMaster": false,
      "positionsMaster": false,
      "authoritiesMaster": false,
      "usersMaster": false,
      "directoriesMaster": false,
      "tagsMaster": false,
      "performancesMaster": false,
      "skillsMaster": false,
      "yearScheduleMaster": false,
      "qualityTargetMaster": false,
      "internalAuditMaster": false,
      "templatesMaster": false,
      "documentSelectionMaster": false,
      "approvalRoutesMaster": false,
      "mailSettingsMaster": false,
      "changedMasterHistory": false,
      "modeSwitching": false,
      "editSchedule": false,
      "absenceInformed": false,
      "templateRevisionCompleteInformed": false,
      "isProgressManagement": false,
      "confirmInform": false,
      "confirmPublish": false,
      "displayHistory": false,
      "correctiveInformed": false,
      "changeResponsible": false,
      "startCirculation": false,
      "templateWithdraw": false,
      "editableInternalAuditPlan": false,
      "changeResponsibleInternalAudit": false
  },
  {
      "id": "6aa310c4-483c-41d2-ba48-a42ec65a705b",
      "title": "計画編集権限",
      "personalSchedule": false,
      "departmentPlan": false,
      "yearSchedule": false,
      "message": false,
      "creation": false,
      "creationList": false,
      "requestList": false,
      "release": false,
      "documentAndRecordSearch": false,
      "editPublishSettings": false,
      "readingStatus": false,
      "editVersionNumber": false,
      "fileUpload": false,
      "corrective": false,
      "internalAuditCorrective": false,
      "internalAuditPlanList": false,
      "internalAuditList": false,
      "internalAuditMemberList": false,
      "personalMenu": false,
      "evaluatorMenu": false,
      "skillEvaluationPlan": false,
      "specificBusinessList": false,
      "documentAndRecord": false,
      "correctiveReport": false,
      "internalAuditReport": false,
      "fishbone": false,
      "organizationsMaster": false,
      "positionsMaster": false,
      "authoritiesMaster": false,
      "usersMaster": false,
      "directoriesMaster": false,
      "tagsMaster": false,
      "performancesMaster": false,
      "skillsMaster": false,
      "yearScheduleMaster": false,
      "qualityTargetMaster": false,
      "internalAuditMaster": false,
      "templatesMaster": false,
      "documentSelectionMaster": false,
      "approvalRoutesMaster": false,
      "mailSettingsMaster": false,
      "changedMasterHistory": false,
      "modeSwitching": false,
      "editSchedule": true,
      "absenceInformed": false,
      "templateRevisionCompleteInformed": false,
      "isProgressManagement": false,
      "confirmInform": false,
      "confirmPublish": false,
      "displayHistory": false,
      "correctiveInformed": false,
      "changeResponsible": false,
      "startCirculation": false,
      "templateWithdraw": false,
      "editableInternalAuditPlan": false,
      "changeResponsibleInternalAudit": false
  },
  {
      "id": "91152d03-8bd4-400e-acad-882e506cdc0b",
      "title": "ワークフロー担当者不在通知先",
      "personalSchedule": false,
      "departmentPlan": false,
      "yearSchedule": false,
      "message": false,
      "creation": false,
      "creationList": false,
      "requestList": false,
      "release": false,
      "documentAndRecordSearch": false,
      "editPublishSettings": false,
      "readingStatus": false,
      "editVersionNumber": false,
      "fileUpload": false,
      "corrective": false,
      "internalAuditCorrective": false,
      "internalAuditPlanList": false,
      "internalAuditList": false,
      "internalAuditMemberList": false,
      "personalMenu": false,
      "evaluatorMenu": false,
      "skillEvaluationPlan": false,
      "specificBusinessList": false,
      "documentAndRecord": false,
      "correctiveReport": false,
      "internalAuditReport": false,
      "fishbone": false,
      "organizationsMaster": false,
      "positionsMaster": false,
      "authoritiesMaster": false,
      "usersMaster": false,
      "directoriesMaster": false,
      "tagsMaster": false,
      "performancesMaster": false,
      "skillsMaster": false,
      "yearScheduleMaster": false,
      "qualityTargetMaster": false,
      "internalAuditMaster": false,
      "templatesMaster": false,
      "documentSelectionMaster": false,
      "approvalRoutesMaster": false,
      "mailSettingsMaster": false,
      "changedMasterHistory": false,
      "modeSwitching": false,
      "editSchedule": false,
      "absenceInformed": true,
      "templateRevisionCompleteInformed": false,
      "isProgressManagement": false,
      "confirmInform": false,
      "confirmPublish": false,
      "displayHistory": false,
      "correctiveInformed": false,
      "changeResponsible": false,
      "startCirculation": false,
      "templateWithdraw": false,
      "editableInternalAuditPlan": false,
      "changeResponsibleInternalAudit": false
  },
  {
      "id": "c26efcca-0b6f-463e-b129-2db9f9a54fb2",
      "title": "テンプレート改定完了通知先",
      "personalSchedule": false,
      "departmentPlan": false,
      "yearSchedule": false,
      "message": false,
      "creation": false,
      "creationList": false,
      "requestList": false,
      "release": false,
      "documentAndRecordSearch": false,
      "editPublishSettings": false,
      "readingStatus": false,
      "editVersionNumber": false,
      "fileUpload": false,
      "corrective": false,
      "internalAuditCorrective": false,
      "internalAuditPlanList": false,
      "internalAuditList": false,
      "internalAuditMemberList": false,
      "personalMenu": false,
      "evaluatorMenu": false,
      "skillEvaluationPlan": false,
      "specificBusinessList": false,
      "documentAndRecord": false,
      "correctiveReport": false,
      "internalAuditReport": false,
      "fishbone": false,
      "organizationsMaster": false,
      "positionsMaster": false,
      "authoritiesMaster": false,
      "usersMaster": false,
      "directoriesMaster": false,
      "tagsMaster": false,
      "performancesMaster": false,
      "skillsMaster": false,
      "yearScheduleMaster": false,
      "qualityTargetMaster": false,
      "internalAuditMaster": false,
      "templatesMaster": false,
      "documentSelectionMaster": false,
      "approvalRoutesMaster": false,
      "mailSettingsMaster": false,
      "changedMasterHistory": false,
      "modeSwitching": false,
      "editSchedule": false,
      "absenceInformed": false,
      "templateRevisionCompleteInformed": true,
      "isProgressManagement": false,
      "confirmInform": false,
      "confirmPublish": false,
      "displayHistory": false,
      "correctiveInformed": false,
      "changeResponsible": false,
      "startCirculation": false,
      "templateWithdraw": false,
      "editableInternalAuditPlan": false,
      "changeResponsibleInternalAudit": false
  },
  {
      "id": "5f44dc98-ee7e-4587-8fbf-fb9f080b392b",
      "title": "進捗管理確認権限",
      "personalSchedule": false,
      "departmentPlan": false,
      "yearSchedule": false,
      "message": false,
      "creation": false,
      "creationList": false,
      "requestList": false,
      "release": false,
      "documentAndRecordSearch": false,
      "editPublishSettings": false,
      "readingStatus": false,
      "editVersionNumber": false,
      "fileUpload": false,
      "corrective": false,
      "internalAuditCorrective": false,
      "internalAuditPlanList": false,
      "internalAuditList": false,
      "internalAuditMemberList": false,
      "personalMenu": false,
      "evaluatorMenu": false,
      "skillEvaluationPlan": false,
      "specificBusinessList": false,
      "documentAndRecord": false,
      "correctiveReport": false,
      "internalAuditReport": false,
      "fishbone": false,
      "organizationsMaster": false,
      "positionsMaster": false,
      "authoritiesMaster": false,
      "usersMaster": false,
      "directoriesMaster": false,
      "tagsMaster": false,
      "performancesMaster": false,
      "skillsMaster": false,
      "yearScheduleMaster": false,
      "qualityTargetMaster": false,
      "internalAuditMaster": false,
      "templatesMaster": false,
      "documentSelectionMaster": false,
      "approvalRoutesMaster": false,
      "mailSettingsMaster": false,
      "changedMasterHistory": false,
      "modeSwitching": false,
      "editSchedule": false,
      "absenceInformed": false,
      "templateRevisionCompleteInformed": false,
      "isProgressManagement": true,
      "confirmInform": false,
      "confirmPublish": false,
      "displayHistory": false,
      "correctiveInformed": false,
      "changeResponsible": false,
      "startCirculation": false,
      "templateWithdraw": false,
      "editableInternalAuditPlan": false,
      "changeResponsibleInternalAudit": false
  },
  {
      "id": "4db5a9db-a2b3-475a-a227-fc564af89bd4",
      "title": "周知確認権限",
      "personalSchedule": false,
      "departmentPlan": false,
      "yearSchedule": false,
      "message": false,
      "creation": false,
      "creationList": false,
      "requestList": false,
      "release": false,
      "documentAndRecordSearch": false,
      "editPublishSettings": false,
      "readingStatus": false,
      "editVersionNumber": false,
      "fileUpload": false,
      "corrective": false,
      "internalAuditCorrective": false,
      "internalAuditPlanList": false,
      "internalAuditList": false,
      "internalAuditMemberList": false,
      "personalMenu": false,
      "evaluatorMenu": false,
      "skillEvaluationPlan": false,
      "specificBusinessList": false,
      "documentAndRecord": false,
      "correctiveReport": false,
      "internalAuditReport": false,
      "fishbone": false,
      "organizationsMaster": false,
      "positionsMaster": false,
      "authoritiesMaster": false,
      "usersMaster": false,
      "directoriesMaster": false,
      "tagsMaster": false,
      "performancesMaster": false,
      "skillsMaster": false,
      "yearScheduleMaster": false,
      "qualityTargetMaster": false,
      "internalAuditMaster": false,
      "templatesMaster": false,
      "documentSelectionMaster": false,
      "approvalRoutesMaster": false,
      "mailSettingsMaster": false,
      "changedMasterHistory": false,
      "modeSwitching": false,
      "editSchedule": false,
      "absenceInformed": false,
      "templateRevisionCompleteInformed": false,
      "isProgressManagement": false,
      "confirmInform": true,
      "confirmPublish": false,
      "displayHistory": false,
      "correctiveInformed": false,
      "changeResponsible": false,
      "startCirculation": false,
      "templateWithdraw": false,
      "editableInternalAuditPlan": false,
      "changeResponsibleInternalAudit": false
  },
  {
      "id": "9795400e-344e-4a56-ad75-7fa75d5f6ef0",
      "title": "発行状況確認権限",
      "personalSchedule": false,
      "departmentPlan": false,
      "yearSchedule": false,
      "message": false,
      "creation": false,
      "creationList": false,
      "requestList": false,
      "release": false,
      "documentAndRecordSearch": false,
      "editPublishSettings": false,
      "readingStatus": false,
      "editVersionNumber": false,
      "fileUpload": false,
      "corrective": false,
      "internalAuditCorrective": false,
      "internalAuditPlanList": false,
      "internalAuditList": false,
      "internalAuditMemberList": false,
      "personalMenu": false,
      "evaluatorMenu": false,
      "skillEvaluationPlan": false,
      "specificBusinessList": false,
      "documentAndRecord": false,
      "correctiveReport": false,
      "internalAuditReport": false,
      "fishbone": false,
      "organizationsMaster": false,
      "positionsMaster": false,
      "authoritiesMaster": false,
      "usersMaster": false,
      "directoriesMaster": false,
      "tagsMaster": false,
      "performancesMaster": false,
      "skillsMaster": false,
      "yearScheduleMaster": false,
      "qualityTargetMaster": false,
      "internalAuditMaster": false,
      "templatesMaster": false,
      "documentSelectionMaster": false,
      "approvalRoutesMaster": false,
      "mailSettingsMaster": false,
      "changedMasterHistory": false,
      "modeSwitching": false,
      "editSchedule": false,
      "absenceInformed": false,
      "templateRevisionCompleteInformed": false,
      "isProgressManagement": false,
      "confirmInform": false,
      "confirmPublish": true,
      "displayHistory": false,
      "correctiveInformed": false,
      "changeResponsible": false,
      "startCirculation": false,
      "templateWithdraw": false,
      "editableInternalAuditPlan": false,
      "changeResponsibleInternalAudit": false
  },
  {
      "id": "97062e60-554d-41e4-bf5b-22060f77c4b8",
      "title": "旧版廃版閲覧権限",
      "personalSchedule": false,
      "departmentPlan": false,
      "yearSchedule": false,
      "message": false,
      "creation": false,
      "creationList": false,
      "requestList": false,
      "release": false,
      "documentAndRecordSearch": false,
      "editPublishSettings": false,
      "readingStatus": false,
      "editVersionNumber": false,
      "fileUpload": false,
      "corrective": false,
      "internalAuditCorrective": false,
      "internalAuditPlanList": false,
      "internalAuditList": false,
      "internalAuditMemberList": false,
      "personalMenu": false,
      "evaluatorMenu": false,
      "skillEvaluationPlan": false,
      "specificBusinessList": false,
      "documentAndRecord": false,
      "correctiveReport": false,
      "internalAuditReport": false,
      "fishbone": false,
      "organizationsMaster": false,
      "positionsMaster": false,
      "authoritiesMaster": false,
      "usersMaster": false,
      "directoriesMaster": false,
      "tagsMaster": false,
      "performancesMaster": false,
      "skillsMaster": false,
      "yearScheduleMaster": false,
      "qualityTargetMaster": false,
      "internalAuditMaster": false,
      "templatesMaster": false,
      "documentSelectionMaster": false,
      "approvalRoutesMaster": false,
      "mailSettingsMaster": false,
      "changedMasterHistory": false,
      "modeSwitching": false,
      "editSchedule": false,
      "absenceInformed": false,
      "templateRevisionCompleteInformed": false,
      "isProgressManagement": false,
      "confirmInform": false,
      "confirmPublish": false,
      "displayHistory": true,
      "correctiveInformed": false,
      "changeResponsible": false,
      "startCirculation": false,
      "templateWithdraw": false,
      "editableInternalAuditPlan": false,
      "changeResponsibleInternalAudit": false
  },
  {
      "id": "2920792c-b9a7-470e-987c-43694cdfaed5",
      "title": "不適合事例報告通知先",
      "personalSchedule": false,
      "departmentPlan": false,
      "yearSchedule": false,
      "message": false,
      "creation": false,
      "creationList": false,
      "requestList": false,
      "release": false,
      "documentAndRecordSearch": false,
      "editPublishSettings": false,
      "readingStatus": false,
      "editVersionNumber": false,
      "fileUpload": false,
      "corrective": false,
      "internalAuditCorrective": false,
      "internalAuditPlanList": false,
      "internalAuditList": false,
      "internalAuditMemberList": false,
      "personalMenu": false,
      "evaluatorMenu": false,
      "skillEvaluationPlan": false,
      "specificBusinessList": false,
      "documentAndRecord": false,
      "correctiveReport": false,
      "internalAuditReport": false,
      "fishbone": false,
      "organizationsMaster": false,
      "positionsMaster": false,
      "authoritiesMaster": false,
      "usersMaster": false,
      "directoriesMaster": false,
      "tagsMaster": false,
      "performancesMaster": false,
      "skillsMaster": false,
      "yearScheduleMaster": false,
      "qualityTargetMaster": false,
      "internalAuditMaster": false,
      "templatesMaster": false,
      "documentSelectionMaster": false,
      "approvalRoutesMaster": false,
      "mailSettingsMaster": false,
      "changedMasterHistory": false,
      "modeSwitching": false,
      "editSchedule": false,
      "absenceInformed": false,
      "templateRevisionCompleteInformed": false,
      "isProgressManagement": false,
      "confirmInform": false,
      "confirmPublish": false,
      "displayHistory": false,
      "correctiveInformed": true,
      "changeResponsible": false,
      "startCirculation": false,
      "templateWithdraw": false,
      "editableInternalAuditPlan": false,
      "changeResponsibleInternalAudit": false
  },
  {
      "id": "3f4c476e-1afa-4d7e-b831-8ced1c37d2ea",
      "title": "是正処置担当者変更権限",
      "personalSchedule": false,
      "departmentPlan": false,
      "yearSchedule": false,
      "message": false,
      "creation": false,
      "creationList": false,
      "requestList": false,
      "release": false,
      "documentAndRecordSearch": false,
      "editPublishSettings": false,
      "readingStatus": false,
      "editVersionNumber": false,
      "fileUpload": false,
      "corrective": false,
      "internalAuditCorrective": false,
      "internalAuditPlanList": false,
      "internalAuditList": false,
      "internalAuditMemberList": false,
      "personalMenu": false,
      "evaluatorMenu": false,
      "skillEvaluationPlan": false,
      "specificBusinessList": false,
      "documentAndRecord": false,
      "correctiveReport": false,
      "internalAuditReport": false,
      "fishbone": false,
      "organizationsMaster": false,
      "positionsMaster": false,
      "authoritiesMaster": false,
      "usersMaster": false,
      "directoriesMaster": false,
      "tagsMaster": false,
      "performancesMaster": false,
      "skillsMaster": false,
      "yearScheduleMaster": false,
      "qualityTargetMaster": false,
      "internalAuditMaster": false,
      "templatesMaster": false,
      "documentSelectionMaster": false,
      "approvalRoutesMaster": false,
      "mailSettingsMaster": false,
      "changedMasterHistory": false,
      "modeSwitching": false,
      "editSchedule": false,
      "absenceInformed": false,
      "templateRevisionCompleteInformed": false,
      "isProgressManagement": false,
      "confirmInform": false,
      "confirmPublish": false,
      "displayHistory": false,
      "correctiveInformed": false,
      "changeResponsible": true,
      "startCirculation": false,
      "templateWithdraw": false,
      "editableInternalAuditPlan": false,
      "changeResponsibleInternalAudit": false
  },
  {
      "id": "f8dd00b0-1718-4b6b-a087-aac3507dc655",
      "title": "是正処置回覧開始権限",
      "personalSchedule": false,
      "departmentPlan": false,
      "yearSchedule": false,
      "message": false,
      "creation": false,
      "creationList": false,
      "requestList": false,
      "release": false,
      "documentAndRecordSearch": false,
      "editPublishSettings": false,
      "readingStatus": false,
      "editVersionNumber": false,
      "fileUpload": false,
      "corrective": false,
      "internalAuditCorrective": false,
      "internalAuditPlanList": false,
      "internalAuditList": false,
      "internalAuditMemberList": false,
      "personalMenu": false,
      "evaluatorMenu": false,
      "skillEvaluationPlan": false,
      "specificBusinessList": false,
      "documentAndRecord": false,
      "correctiveReport": false,
      "internalAuditReport": false,
      "fishbone": false,
      "organizationsMaster": false,
      "positionsMaster": false,
      "authoritiesMaster": false,
      "usersMaster": false,
      "directoriesMaster": false,
      "tagsMaster": false,
      "performancesMaster": false,
      "skillsMaster": false,
      "yearScheduleMaster": false,
      "qualityTargetMaster": false,
      "internalAuditMaster": false,
      "templatesMaster": false,
      "documentSelectionMaster": false,
      "approvalRoutesMaster": false,
      "mailSettingsMaster": false,
      "changedMasterHistory": false,
      "modeSwitching": false,
      "editSchedule": false,
      "absenceInformed": false,
      "templateRevisionCompleteInformed": false,
      "isProgressManagement": false,
      "confirmInform": false,
      "confirmPublish": false,
      "displayHistory": false,
      "correctiveInformed": false,
      "changeResponsible": false,
      "startCirculation": true,
      "templateWithdraw": false,
      "editableInternalAuditPlan": false,
      "changeResponsibleInternalAudit": false
  },
  {
      "id": "f06a3775-536b-46ca-8c4b-2e8e60573c4a",
      "title": "テンプレート改定申請取下げ権限",
      "personalSchedule": false,
      "departmentPlan": false,
      "yearSchedule": false,
      "message": false,
      "creation": false,
      "creationList": false,
      "requestList": false,
      "release": false,
      "documentAndRecordSearch": false,
      "editPublishSettings": false,
      "readingStatus": false,
      "editVersionNumber": false,
      "fileUpload": false,
      "corrective": false,
      "internalAuditCorrective": false,
      "internalAuditPlanList": false,
      "internalAuditList": false,
      "internalAuditMemberList": false,
      "personalMenu": false,
      "evaluatorMenu": false,
      "skillEvaluationPlan": false,
      "specificBusinessList": false,
      "documentAndRecord": false,
      "correctiveReport": false,
      "internalAuditReport": false,
      "fishbone": false,
      "organizationsMaster": false,
      "positionsMaster": false,
      "authoritiesMaster": false,
      "usersMaster": false,
      "directoriesMaster": false,
      "tagsMaster": false,
      "performancesMaster": false,
      "skillsMaster": false,
      "yearScheduleMaster": false,
      "qualityTargetMaster": false,
      "internalAuditMaster": false,
      "templatesMaster": false,
      "documentSelectionMaster": false,
      "approvalRoutesMaster": false,
      "mailSettingsMaster": false,
      "changedMasterHistory": false,
      "modeSwitching": false,
      "editSchedule": false,
      "absenceInformed": false,
      "templateRevisionCompleteInformed": false,
      "isProgressManagement": false,
      "confirmInform": false,
      "confirmPublish": false,
      "displayHistory": false,
      "correctiveInformed": false,
      "changeResponsible": false,
      "startCirculation": false,
      "templateWithdraw": true,
      "editableInternalAuditPlan": false,
      "changeResponsibleInternalAudit": false
  },
  {
      "id": "a8bd796e-db58-4113-b66b-7563f0324604",
      "title": "内部監査計画作成権限",
      "personalSchedule": false,
      "departmentPlan": false,
      "yearSchedule": false,
      "message": false,
      "creation": false,
      "creationList": false,
      "requestList": false,
      "release": false,
      "documentAndRecordSearch": false,
      "editPublishSettings": false,
      "readingStatus": false,
      "editVersionNumber": false,
      "fileUpload": false,
      "corrective": false,
      "internalAuditCorrective": false,
      "internalAuditPlanList": false,
      "internalAuditList": false,
      "internalAuditMemberList": false,
      "personalMenu": false,
      "evaluatorMenu": false,
      "skillEvaluationPlan": false,
      "specificBusinessList": false,
      "documentAndRecord": false,
      "correctiveReport": false,
      "internalAuditReport": false,
      "fishbone": false,
      "organizationsMaster": false,
      "positionsMaster": false,
      "authoritiesMaster": false,
      "usersMaster": false,
      "directoriesMaster": false,
      "tagsMaster": false,
      "performancesMaster": false,
      "skillsMaster": false,
      "yearScheduleMaster": false,
      "qualityTargetMaster": false,
      "internalAuditMaster": false,
      "templatesMaster": false,
      "documentSelectionMaster": false,
      "approvalRoutesMaster": false,
      "mailSettingsMaster": false,
      "changedMasterHistory": false,
      "modeSwitching": false,
      "editSchedule": false,
      "absenceInformed": false,
      "templateRevisionCompleteInformed": false,
      "isProgressManagement": false,
      "confirmInform": false,
      "confirmPublish": false,
      "displayHistory": false,
      "correctiveInformed": false,
      "changeResponsible": false,
      "startCirculation": false,
      "templateWithdraw": false,
      "editableInternalAuditPlan": true,
      "changeResponsibleInternalAudit": false
  },
  {
      "id": "5d6765b9-8996-4a5d-b71d-676526fccb67",
      "title": "内部監査担当者変更権限",
      "personalSchedule": false,
      "departmentPlan": false,
      "yearSchedule": false,
      "message": false,
      "creation": false,
      "creationList": false,
      "requestList": false,
      "release": false,
      "documentAndRecordSearch": false,
      "editPublishSettings": false,
      "readingStatus": false,
      "editVersionNumber": false,
      "fileUpload": false,
      "corrective": false,
      "internalAuditCorrective": false,
      "internalAuditPlanList": false,
      "internalAuditList": false,
      "internalAuditMemberList": false,
      "personalMenu": false,
      "evaluatorMenu": false,
      "skillEvaluationPlan": false,
      "specificBusinessList": false,
      "documentAndRecord": false,
      "correctiveReport": false,
      "internalAuditReport": false,
      "fishbone": false,
      "organizationsMaster": false,
      "positionsMaster": false,
      "authoritiesMaster": false,
      "usersMaster": false,
      "directoriesMaster": false,
      "tagsMaster": false,
      "performancesMaster": false,
      "skillsMaster": false,
      "yearScheduleMaster": false,
      "qualityTargetMaster": false,
      "internalAuditMaster": false,
      "templatesMaster": false,
      "documentSelectionMaster": false,
      "approvalRoutesMaster": false,
      "mailSettingsMaster": false,
      "changedMasterHistory": false,
      "modeSwitching": false,
      "editSchedule": false,
      "absenceInformed": false,
      "templateRevisionCompleteInformed": false,
      "isProgressManagement": false,
      "confirmInform": false,
      "confirmPublish": false,
      "displayHistory": false,
      "correctiveInformed": false,
      "changeResponsible": false,
      "startCirculation": false,
      "templateWithdraw": false,
      "editableInternalAuditPlan": false,
      "changeResponsibleInternalAudit": true
  }
];;